jobs:
  - job: build_all_window
    pool:
      vmImage: 'windows-2019'
    variables:
      phpVersion: 7.2
    steps:   
    - powershell: docker images
      # - powershell: .\build.ps1
      #displayName: 'build.ps1'
    - powershell: ./build.ps1
    - powershell: docker cp  ./start.ps1 aelf:/
    - powershell: docker cp  ./dotnet-install.ps1 aelf:/
    - powershell: docker cp  ./scripts/aelf-node/appsettings.json aelf:/
    - powershell: docker cp  ./scripts/aelf-node/keys/SD6BXDrKT2syNd1WehtPyRo3dPBiXqfGUj8UJym7YP9W9RynM.json aelf:/
    - powershell: docker ps
    - powershell: docker exec -it aelf powershell -c "winpty dotnet c:/aelf/aelf-node/AElf.Launcher.dll"
    - script: netstat -an
    # - powershell: powershell.exe -file scripts/aelf-node/deploy-node.ps1
    #   displayName: 'deploy a full node'
    # - script: |
    #       cp scripts/aelf-node/php.ini /c/tools/php/php.ini
    #       php -c /c/tools/php/php.ini
    # - script: |
    #     php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
    #     php composer-setup.php
    #     php composer.phar config -g repo.packagist composer https://packagist.phpcomposer.com
    #     php composer.phar install --no-interaction --prefer-dist
    #   displayName: 'composer install'
    # - powershell: php phpunit.phar --bootstrap bootstrap.php tests/AElfTest.php 
    #   displayName: 'test'
