jobs:
  - job: build_all_window
    pool:
      vmImage: 'windows-2019'
    variables:
      phpVersion: 7.2
    steps:   
    - script: |
        git clone https://github.com/ideawu/ssdb-bin.git
        cp scripts/aelf-node/ssdb.conf ssdb-bin/ssdb.conf
        cd ssdb-bin  
        cat ssdb.conf
        ssdb-server-1.9.4.exe -d ssdb.conf  
        cat log.txt
        netstat -an

    # - powershell: systeminfo
    - powershell: .\redis\test.ps1
    - powershell: .\build.ps1
    - powershell: docker-compose up -d 
    - powershell: docker ps
    - script: netstat -an
    - powershell: sleep 60
    - script: netstat -an
    - powershell: docker ps -a
    # - powershell: powershell.exe -file scripts/aelf-node/deploy-node.ps1
    #   displayName: 'deploy a full node'
    - script: |
          cp scripts/aelf-node/php.ini /c/tools/php/php.ini
          php -c /c/tools/php/php.ini
    - script: |
        php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
        php composer-setup.php
        php composer.phar config -g repo.packagist composer https://packagist.phpcomposer.com
        php composer.phar install --no-interaction --prefer-dist
      displayName: 'composer install'
    - powershell: php phpunit.phar --bootstrap bootstrap.php tests/AElfTest.php 
      displayName: 'test'


# resources:
#   containers:
#   - container: windows
#     image: windows-2019

# jobs:
# - job: RunInContainer
#   pool:
#       vmImage: 'windows-2019'
#   container: mcr.microsoft.com/windows/servercore:ltsc2019
#   steps:
#   - powershell: ./dotnet-install.ps1 -InstallDir '~/.dotnet' -Version '3.1.102'   
#   - powershell: ./scripts/aelf-node/deploy-node.ps1