jobs:
  - job: build_all_window
    pool:
      vmImage: 'windows-2019'
    variables:
      phpVersion: 7.2
    steps:   
    - powershell: docker images
    - powershell: .\build.ps1
      displayName: 'build.ps1'
    # - powershell: sleep 30
    - powershell: docker-compose up -d
    - powershell: docker ps -a
    - script: netstat -an
    - script: sleep 30
    # - powershell: powershell.exe -file scripts/aelf-node/deploy-node.ps1
    #   displayName: 'deploy a full node'
    # - script: |
    #       cp scripts/aelf-node/php.ini /c/tools/php/php.ini
    #       php -c /c/tools/php/php.ini
    # - script: |
    #     php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
    #     php composer-setup.php
    #     php composer.phar config -g repo.packagist composer https://packagist.phpcomposer.com
    #     php composer.phar install --no-interaction --prefer-dist
    #   displayName: 'composer install'
    # - powershell: php phpunit.phar --bootstrap bootstrap.php tests/AElfTest.php 
    #   displayName: 'test'
