# jobs:
#   - deployment: DeployWeb
#     displayName: 'dotnet dll'
#     pool:
#       vmImage: 'windows-2019'
#     environment: 'test'
#     strategy:
#       runOnce:
#         deploy:
#           steps:
#           - powershell: pwd
#           - powershell: ls c:\
#           - powershell: powershell.exe -file .\scripts\aelf-node\deploy-node.ps1
#           - script: |
#               cp scripts/aelf-node/php.ini /c/tools/php/php.ini
#               php -c /c/tools/php/php.ini
#           - script: |
#               php -r "copy('https://install.phpcomposer.com/installer', 'composer-setup.php');"
#               php composer-setup.php
#               php composer.phar config -g repo.packagist composer https://packagist.phpcomposer.com
#               php composer.phar install --no-interaction --prefer-dist
#             displayName: 'composer install'
#           - powershell: php phpunit.phar --bootstrap bootstrap.php tests/AElfTest.php 
#             displayName: 'test'
jobs:
  - deployment: DeployWeb
    displayName: 'dotnet dll'
    pool:
      vmImage: 'windows-2019'
      steps:
        - bash: |
            export IPADDR=$(ip addr | grep 'state UP' -A2 | tail -n1 | awk '{print $2}' | cut -f1  -d'/')
            echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
          condition: eq( variables['Agent.OS'], 'Linux' )
          displayName: Get IP on Linux
# macOS
        - bash: |
            export IPADDR=$(ifconfig | grep 'en0' -A3 | tail -n1 | awk '{print $2}')
            echo "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
          condition: eq( variables['Agent.OS'], 'Darwin' )
          displayName: Get IP on macOS
# Windows
        - powershell: |
            Set-Variable -Name IPADDR -Value ((Get-NetIPAddress | ?{ $_.AddressFamily -eq "IPv4" -and !($_.IPAddress -match "169") -and !($_.IPaddress -match "127") } | Select-Object -First 1).IPAddress)
            Write-Host "##vso[task.setvariable variable=IP_ADDR]$IPADDR"
          condition: eq( variables['Agent.OS'], 'Windows_NT' )
          displayName: Get IP on Windows

# now we use the value, no matter where we got it
        - script: |
          echo The IP address is $(IP_ADDR)